version: 2
linters-settings:
  enable: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: ".*_test\\.go$"
      linters:
        - errcheck
