version: 2
project_name: aws-s3-siggy
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: siggy
    ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - name: siggy
    tap:
      owner: RyuyaIshibashi
      name: homebrew-siggy
    homepage: 'https://github.com/RyuyaIshibashi/aws-s3-siggy'
    description: 'Generate presigned URL for AWS S3'
    license: "MIT"