version: 2
project_name: aws-s3-siggy
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: siggy
    ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: RyuyaIshibashi
      name: homebrew-siggy
    folder: Formula
    homepage: 'https://github.com/RyuyaIshibashi/aws-s3-siggy'
    description: 'Generate presigned URL for AWS S3'
    license: "MIT"